---
openapi: 3.0.1
info:
  title: API V3
  description: |
    # Check financial eligibility for legal aid.

    ## Usage:
      - Create an assessment by POSTing a payload to `/assessments`
        and store the `assessment_id` returned.
      - Add assessment components, such as applicant, capitals and properties using the
        `assessment_id` from the first call
      - Retrieve the result using the GET `/assessments/{assessment_id}`
  contact:
    name: Github repository
    url: https://github.com/ministryofjustice/check-financial-eligibility
  version: v3
paths:
  "/assessments":
    post:
      summary: create assessment
      tags:
      - Assessment
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                client_reference_id:
                  type: string
                  example: LA-FOO-BAR
                  description: Client's reference number for this application (free
                    text)
                submission_date:
                  type: string
                  description: Date of the original submission (iso8601 format)
                  example: '2022-05-19'
                matter_proceeding_type:
                  type: string
                  description: Matter type of the case (v3 and below only)
                  example: domestic_abuse
        required: true
