require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/integration_helpers/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/integration_helpers/*'
    - 'db/migrate/*'

Metrics/ParameterLists:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 180

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Exclude:
    - '**/*'

Style/SymbolArray:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
