require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/HashSyntax:
  Exclude:
    - 'spec/factories/gross_income_summary_factory.rb'
    - 'spec/integration/ap_1367_spec.rb'
    - 'spec/integration/policy_disregards_spec.rb'
    - 'spec/integration/remarks_spec.rb'
