---
gross_income_upper:
  children:
    one: 1
    many: 7
disposable_income_lower: 2000
disposable_income_upper: 20000
capital_lower: 5
capital_upper: 20000
property_notional_sale_costs_percentage: 3.0
property_maximum_mortgage_allowance: 100_000
property_disregard:
  main_home: 100_000
  additional_property: 0.0
vehicle_disregard: 15_000
vehicle_out_of_scope_months: 36
vehicle_capital_value_pctg:
  months:
    12: 100
    24: 80
    36: 60
