---
gross_income_upper:
  children:
    one: 1
    two: 3
    three: 5
    many: 7
disposable_income_lower: 100
disposable_income_upper: 50000
capital_lower: 1
capital_upper: 30000
property_notional_sale_costs_percentage: 3.0
property_maximum_mortgage_allowance: 100_000
property_main_dwelling_disregard: 100_000
