---
gross_income_upper:
  children:
    one: 1
    two: 3
    many: 7
disposable_income_lower: 1000
disposable_income_upper: 10000
capital_lower: 3_000
capital_upper: 8_000
pensioner_capital_disregard:
  minimum_age_in_years: 60
  passported: 100_000
    # disregard to use if monthly disposable income (excluding income derived from capital) is eqqual to or below these figures
  monthly_income_values:
    0: 100_000
    25.01: 90_000
    50.01: 80_000
    75.01: 70_000
    100.01: 60_000
    125.01: 50_000
    150.01: 40_000
    175.01: 30_000
    200.01: 20_000
    225.01: 10_000
    315.01: 0

property_notional_sale_costs_percentage: 3.0
property_maximum_mortgage_allowance: 100_000
property_disregard:
  main_home: 100_000
  additional_property: 0.0
vehicle_disregard: 15_000
vehicle_out_of_scope_months: 36
vehicle_capital_value_pctg:
    months:
      12: 100
      24: 80
      36: 60
